import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'
import Instagram from '../components/Instagram'
import Cards from '../components/Cards'
import Why from '../components/Why'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero heading='Capture photography' message='I capture moments in nature and keep them alive.'/>
      <Why />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
