import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Why from '../components/Why'
import Footer from '../components/Footer'
import Adelanto from '../components/Adelanto'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arma tu toque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero heading='Arma tu toque' message='Hacemos crecer tu comunidad. En contacto directo con tus fans.'/>
      <Why />
      <Adelanto />
      <Footer />
    </div>
  )
}
